"""initial schema

Revision ID: 13c1d504b651
Revises: 
Create Date: 2026-04-15 11:32:04.283753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '13c1d504b651'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slack_team_id', sa.String(length=64), nullable=False),
    sa.Column('slack_user_id', sa.String(length=64), nullable=False),
    sa.Column('github_login', sa.String(length=256), nullable=False),
    sa.Column('activity_type', sa.String(length=64), nullable=False),
    sa.Column('repo_full_name', sa.String(length=256), nullable=False),
    sa.Column('ref_id', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('activity_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_activities_activity_at'), 'github_activities', ['activity_at'], unique=False)
    op.create_index(op.f('ix_github_activities_github_login'), 'github_activities', ['github_login'], unique=False)
    op.create_index(op.f('ix_github_activities_slack_team_id'), 'github_activities', ['slack_team_id'], unique=False)
    op.create_index(op.f('ix_github_activities_slack_user_id'), 'github_activities', ['slack_user_id'], unique=False)
    op.create_index('ix_github_activities_user_ts', 'github_activities', ['github_login', 'activity_at'], unique=False)
    op.create_table('slack_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slack_team_id', sa.String(length=64), nullable=False),
    sa.Column('slack_user_id', sa.String(length=64), nullable=False),
    sa.Column('channel_id', sa.String(length=64), nullable=False),
    sa.Column('channel_name', sa.String(length=256), nullable=True),
    sa.Column('message_ts', sa.String(length=64), nullable=False),
    sa.Column('thread_ts', sa.String(length=64), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('is_standup_channel', sa.Boolean(), nullable=False),
    sa.Column('is_thread_reply', sa.Boolean(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_ts')
    )
    op.create_index('ix_slack_messages_channel', 'slack_messages', ['channel_id', 'message_ts'], unique=False)
    op.create_index(op.f('ix_slack_messages_slack_team_id'), 'slack_messages', ['slack_team_id'], unique=False)
    op.create_index(op.f('ix_slack_messages_slack_user_id'), 'slack_messages', ['slack_user_id'], unique=False)
    op.create_index(op.f('ix_slack_messages_timestamp'), 'slack_messages', ['timestamp'], unique=False)
    op.create_index('ix_slack_messages_user_ts', 'slack_messages', ['slack_user_id', 'message_ts'], unique=False)
    op.create_table('slack_user_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slack_user_id', sa.String(length=64), nullable=False),
    sa.Column('slack_team_id', sa.String(length=64), nullable=False),
    sa.Column('slack_team_name', sa.String(length=256), nullable=True),
    sa.Column('slack_display_name', sa.String(length=256), nullable=True),
    sa.Column('slack_email', sa.String(length=256), nullable=True),
    sa.Column('access_token', sa.String(length=512), nullable=False),
    sa.Column('token_scopes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slack_user_tokens_slack_team_id'), 'slack_user_tokens', ['slack_team_id'], unique=False)
    op.create_index(op.f('ix_slack_user_tokens_slack_user_id'), 'slack_user_tokens', ['slack_user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slack_user_id', sa.String(length=64), nullable=False),
    sa.Column('slack_team_id', sa.String(length=64), nullable=False),
    sa.Column('slack_display_name', sa.String(length=256), nullable=True),
    sa.Column('slack_real_name', sa.String(length=256), nullable=True),
    sa.Column('slack_email', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('opted_in', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_slack_team_id'), 'users', ['slack_team_id'], unique=False)
    op.create_index(op.f('ix_users_slack_user_id'), 'users', ['slack_user_id'], unique=True)
    op.create_table('work_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slack_user_id', sa.String(length=64), nullable=False),
    sa.Column('slack_team_id', sa.String(length=64), nullable=False),
    sa.Column('github_login', sa.String(length=256), nullable=True),
    sa.Column('source', sa.Enum('SLACK', 'GITHUB', name='workunitsource'), nullable=False),
    sa.Column('type', sa.Enum('STANDUP', 'DISCUSSION', 'ANNOUNCEMENT', 'THREAD_REPLY', 'COMMIT', 'PR_OPENED', 'PR_MERGED', 'PR_REVIEW', 'ISSUE_OPENED', 'ISSUE_CLOSED', 'ISSUE_COMMENT', name='workunittype'), nullable=False),
    sa.Column('category', sa.Enum('FEATURE', 'BUG_FIX', 'ARCHITECTURE', 'MENTORSHIP', 'INCIDENT', 'REVIEW', 'DOCUMENTATION', 'PLANNING', 'OPERATIONAL', 'UNKNOWN', name='workcategory'), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('slack_channel_id', sa.String(length=64), nullable=True),
    sa.Column('slack_message_ts', sa.String(length=64), nullable=True),
    sa.Column('github_repo', sa.String(length=256), nullable=True),
    sa.Column('github_ref_id', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ai_extracted_items', sa.JSON(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_units_slack_team_id'), 'work_units', ['slack_team_id'], unique=False)
    op.create_index(op.f('ix_work_units_slack_user_id'), 'work_units', ['slack_user_id'], unique=False)
    op.create_index('ix_work_units_team_ts', 'work_units', ['slack_team_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_work_units_timestamp'), 'work_units', ['timestamp'], unique=False)
    op.create_index('ix_work_units_type', 'work_units', ['type'], unique=False)
    op.create_index('ix_work_units_user_ts', 'work_units', ['slack_user_id', 'timestamp'], unique=False)
    op.create_table('user_github_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slack_user_id', sa.String(length=64), nullable=False),
    sa.Column('slack_team_id', sa.String(length=64), nullable=False),
    sa.Column('github_user_id', sa.Integer(), nullable=True),
    sa.Column('github_login', sa.String(length=256), nullable=True),
    sa.Column('github_access_token', sa.String(length=512), nullable=True),
    sa.Column('github_token_scope', sa.String(length=512), nullable=True),
    sa.Column('linked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['slack_user_id'], ['users.slack_user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slack_user_id', 'slack_team_id')
    )
    op.create_index(op.f('ix_user_github_links_slack_user_id'), 'user_github_links', ['slack_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_github_links_slack_user_id'), table_name='user_github_links')
    op.drop_table('user_github_links')
    op.drop_index('ix_work_units_user_ts', table_name='work_units')
    op.drop_index('ix_work_units_type', table_name='work_units')
    op.drop_index(op.f('ix_work_units_timestamp'), table_name='work_units')
    op.drop_index('ix_work_units_team_ts', table_name='work_units')
    op.drop_index(op.f('ix_work_units_slack_user_id'), table_name='work_units')
    op.drop_index(op.f('ix_work_units_slack_team_id'), table_name='work_units')
    op.drop_table('work_units')
    op.drop_index(op.f('ix_users_slack_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_slack_team_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_slack_user_tokens_slack_user_id'), table_name='slack_user_tokens')
    op.drop_index(op.f('ix_slack_user_tokens_slack_team_id'), table_name='slack_user_tokens')
    op.drop_table('slack_user_tokens')
    op.drop_index('ix_slack_messages_user_ts', table_name='slack_messages')
    op.drop_index(op.f('ix_slack_messages_timestamp'), table_name='slack_messages')
    op.drop_index(op.f('ix_slack_messages_slack_user_id'), table_name='slack_messages')
    op.drop_index(op.f('ix_slack_messages_slack_team_id'), table_name='slack_messages')
    op.drop_index('ix_slack_messages_channel', table_name='slack_messages')
    op.drop_table('slack_messages')
    op.drop_index('ix_github_activities_user_ts', table_name='github_activities')
    op.drop_index(op.f('ix_github_activities_slack_user_id'), table_name='github_activities')
    op.drop_index(op.f('ix_github_activities_slack_team_id'), table_name='github_activities')
    op.drop_index(op.f('ix_github_activities_github_login'), table_name='github_activities')
    op.drop_index(op.f('ix_github_activities_activity_at'), table_name='github_activities')
    op.drop_table('github_activities')
    # ### end Alembic commands ###
