"""add team_members table

Revision ID: 20770f2a5874
Revises: 13c1d504b651
Create Date: 2026-04-15 12:00:14.673337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20770f2a5874'
down_revision: Union[str, None] = '13c1d504b651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manager_slack_user_id', sa.String(length=64), nullable=False),
    sa.Column('manager_slack_team_id', sa.String(length=64), nullable=False),
    sa.Column('member_slack_user_id', sa.String(length=64), nullable=False),
    sa.Column('member_slack_team_id', sa.String(length=64), nullable=False),
    sa.Column('member_display_name', sa.String(length=256), nullable=True),
    sa.Column('member_real_name', sa.String(length=256), nullable=True),
    sa.Column('member_avatar_url', sa.String(length=512), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manager_slack_user_id', 'member_slack_user_id')
    )
    op.create_index(op.f('ix_team_members_manager_slack_team_id'), 'team_members', ['manager_slack_team_id'], unique=False)
    op.create_index(op.f('ix_team_members_manager_slack_user_id'), 'team_members', ['manager_slack_user_id'], unique=False)
    op.create_index(op.f('ix_team_members_member_slack_user_id'), 'team_members', ['member_slack_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_members_member_slack_user_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_manager_slack_user_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_manager_slack_team_id'), table_name='team_members')
    op.drop_table('team_members')
    # ### end Alembic commands ###
