"""add email and github_login to team_members

Revision ID: a0396ef840cb
Revises: 20770f2a5874
Create Date: 2026-04-15 12:11:37.216951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a0396ef840cb'
down_revision: Union[str, None] = '20770f2a5874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_members', sa.Column('member_email', sa.String(length=256), nullable=True))
    op.add_column('team_members', sa.Column('github_login', sa.String(length=256), nullable=True))
    op.add_column('team_members', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_members', 'updated_at')
    op.drop_column('team_members', 'github_login')
    op.drop_column('team_members', 'member_email')
    # ### end Alembic commands ###
